const plays = [
  { id:'sick-hershey-vision', lane:'Vision / sensing', signal:'SICK Ruler3000 / 3D vision update', account:'Hershey Edgerton', line:'SICK', trigger:'Packaging/palletizing SKU matrix creates case orientation, inspection, reject timing, and quality-data opportunities.', pkg:['3D vision feasibility screen','PLC result mapping','Reject timing verification','Camera/network architecture review'], value:'$18k–$65k', priority:'A', confidence:'High', buyer:'Engineering / packaging operations' },
  { id:'phoenix-tna-network', lane:'Panel reliability', signal:'Phoenix Contact panel reliability kit', account:'TNA Robag / food packaging site', line:'Phoenix Contact', trigger:'Service-network issues and field notes suggest panel power, terminal, switch, and documentation cleanup.', pkg:['24VDC health check','Industrial switch map','Terminal/relay cleanup','Documented service-network path'], value:'$8k–$28k', priority:'B+', confidence:'Medium-high', buyer:'Maintenance / controls' },
  { id:'schneider-modernization', lane:'Controls modernization', signal:'Schneider controls modernization', account:'Schneider-heavy plant panel', line:'Schneider Electric', trigger:'Schneider spans 25 TCAS line-card categories, so one panel review can create PLC/HMI/VFD/safety opportunities.', pkg:['PLC/HMI lifecycle review','VFD spare path','Panel risk report','Software/backup assessment'], value:'$25k–$140k', priority:'A', confidence:'High', buyer:'Plant engineering' },
  { id:'redlion-data', lane:'Data access', signal:'Red Lion / HMS / Turck data access', account:'Warehouse automation prospect', line:'Red Lion / Turck / HMS', trigger:'Customer wants machine data without a full PLC rewrite; gateways create a practical first project.', pkg:['Protocol gateway review','SCADA/OEE signal map','Industrial Ethernet cleanup','Pilot data dashboard'], value:'$12k–$55k', priority:'A-', confidence:'Medium-high', buyer:'Operations / IT-OT' },
  { id:'berobox-palletizer', lane:'Palletizing automation', signal:'beRobox palletizer fit screen', account:'Hershey Edgerton', line:'Palletizing automation', trigger:'Hershey SKU weights/rates make a plug-and-play palletizer screen credible, but safety/control details need verification.', pkg:['SKU/rate fit matrix','Safety + controls checklist','Infeed/outfeed integration scope','Vendor question pack'], value:'$20k–$90k', priority:'A-', confidence:'Medium', buyer:'Packaging engineering' },
  { id:'drives-spares', lane:'Critical spares', signal:'Drive replacement / critical spares', account:'Dormant food plant account', line:'Schneider / Toshiba / Control Techniques', trigger:'Drive failures create urgent buys; proactive spare mapping turns risk into parts revenue.', pkg:['Critical drive inventory','Replacement cross-reference','Spare quote package','Maintenance handoff sheet'], value:'$10k–$75k', priority:'B+', confidence:'Medium', buyer:'Maintenance manager' },
  { id:'hmi-retrofit', lane:'HMI retrofit', signal:'Legacy HMI backup and retrofit campaign', account:'Multi-site manufacturing account', line:'Pro-face / Red Lion / Schneider / IDEC', trigger:'Old HMIs are visible in panel photos and often lack backups, replacement paths, or readable screens.', pkg:['HMI inventory','Backup status check','Replacement path','Operator-screen readability review'], value:'$7k–$45k', priority:'B+', confidence:'Medium', buyer:'Controls engineer' }
];
const focusText = { new_product:'new product / solution update', spares:'critical spares / replacement path', risk:'obsolescence or downtime risk', data:'machine data / reporting wedge', campaign:'multi-account product campaign' };
const signalGroups = [
  ['Schneider Electric','Controls, drives, HMIs, software, safety','Modernization, lifecycle, spares, panel standards'],
  ['SICK','Sensors, safety, encoders, software, 3D vision','Inspection, safety audits, reject issues, quality data'],
  ['Phoenix Contact','Power, relays, terminals, datacom, PLCs','Panel reliability, network documentation, 24V issues'],
  ['Red Lion / Turck / HMS','Gateways, HMIs, I/O, wireless, interfaces','Machine data access, protocol conversion, OT visibility'],
  ['IDEC / Pro-face','HMIs, PLCs, relays, pilot devices','HMI retrofit, operator interface backups'],
  ['Toshiba / Control Techniques / KB','Drives and motion','Critical spare drives, replacements, failure risk']
];
let currentPlay = plays[0];
let currentPacket = null;
let queue = JSON.parse(localStorage.getItem('tcasRevenueRadarQueue') || '[]');
const $ = id => document.getElementById(id);
function log(msg){ const stamp = new Date().toLocaleTimeString([], {hour:'2-digit', minute:'2-digit', second:'2-digit'}); $('actionLog').textContent = `[${stamp}] ${msg}\n` + $('actionLog').textContent.split('\n').slice(0,8).join('\n'); }
function csvEscape(v){ return `"${String(v ?? '').replaceAll('"','""')}"`; }
function saveQueue(){ localStorage.setItem('tcasRevenueRadarQueue', JSON.stringify(queue)); updateCounts(); renderQueue(); }
function updateCounts(){ $('queueCount').textContent = queue.length; $('approvedCount').textContent = queue.filter(q=>q.status==='approved').length; }
function focus(){ return focusText[$('focusSelect').value]; }
function packetFor(play){ const packet = {
  id: `${play.id}-${Date.now()}`,
  playId: play.id,
  created: new Date().toISOString(),
  account: play.account,
  signal: play.signal,
  line: play.line,
  lane: play.lane,
  priority: play.priority,
  confidence: play.confidence,
  value: play.value,
  buyer: play.buyer,
  focus: focus(),
  status: 'needs_review',
  summary: `${play.account} has a ${focus()} opportunity tied to ${play.line}. ${play.trigger} This is line-card pull-through: a manufacturer-specific reason to call, not generic newsletter content.`,
  pkg: play.pkg,
  draft: `Subject: TCAS idea for ${play.account}\n\nHi [Name],\n\nWe saw a ${play.line} update that may matter for your operation. Based on what we know so far, the practical angle is ${focus()}: ${play.trigger}\n\nTCAS can help with:\n${play.pkg.map(x=>'• '+x).join('\n')}\n\nI do not want to assume fit without checking the details. If useful, TCAS can turn this into a short review with current state, recommended path, and quote-ready parts where appropriate.\n\nThanks,\nTCAS`,
  crm: `account: ${play.account}\nsignal: ${play.signal}\nmanufacturer_line: ${play.line}\nlane: ${play.lane}\ncommercial_focus: ${focus()}\nestimated_value: ${play.value}\npriority: ${play.priority}\nconfidence: ${play.confidence}\nbuyer: ${play.buyer}\nstatus: needs_review\nnext_step: verify technical fit and approve outreach`
}; return packet; }
function build(play=currentPlay){ currentPlay = play; currentPacket = packetFor(play); $('priority').textContent = currentPacket.priority; $('value').textContent = currentPacket.value; $('packetStatus').textContent = 'Draft'; $('summary').textContent = currentPacket.summary; $('packageList').innerHTML = currentPacket.pkg.map(x=>`<li>${x}</li>`).join(''); $('draft').textContent = currentPacket.draft; $('crm').textContent = currentPacket.crm; log(`Built packet: ${play.account} · ${play.signal}`); }
function renderRadar(){ const q = $('searchInput').value.toLowerCase(); const lane = $('laneFilter').value; const grid = $('radarGrid'); grid.innerHTML=''; plays.filter(p => (lane==='all'||p.lane===lane) && [p.account,p.signal,p.line,p.lane,p.trigger].join(' ').toLowerCase().includes(q)).forEach(play=>{ const card=document.createElement('article'); card.className='radar-card'; card.innerHTML=`<div class="radar-top"><span>${play.priority} priority</span><span>${play.value}</span></div><h3>${play.signal}</h3><p><b>${play.account}</b> · ${play.line}</p><p>${play.trigger}</p><div class="mini-actions"><button data-action="build">Build play</button><button data-action="queue">Add to queue</button></div>`; card.querySelector('[data-action="build"]').onclick=()=>{ $('playSelect').value=play.id; build(play); document.querySelector('#builder').scrollIntoView({behavior:'smooth'}); }; card.querySelector('[data-action="queue"]').onclick=()=>{ $('playSelect').value=play.id; build(play); addToQueue(); }; grid.appendChild(card); }); if(!grid.children.length){ grid.innerHTML='<div class="empty">No matching plays. Clear search/filter.</div>'; }}
function renderQueue(){ const wrap=$('queueList'); if(!queue.length){ wrap.innerHTML='<div class="empty">No queued packets yet. Click “Add to approval queue” from a play.</div>'; return; } wrap.innerHTML = queue.map(item=>`<article class="queue-item ${item.status}"><div><div class="queue-title">${item.account}</div><div class="queue-meta">${item.signal} · ${item.line} · ${item.value}</div><p>${item.summary}</p></div><div class="queue-controls"><span class="status ${item.status}">${item.status.replace('_',' ')}</span><button data-id="${item.id}" data-act="approve">Approve</button><button data-id="${item.id}" data-act="reject">Reject</button><button data-id="${item.id}" data-act="copy">Copy draft</button><button data-id="${item.id}" data-act="remove">Remove</button></div></article>`).join(''); wrap.querySelectorAll('button').forEach(btn=>btn.onclick=()=>handleQueue(btn.dataset.id, btn.dataset.act)); }
function handleQueue(id, act){ const item=queue.find(q=>q.id===id); if(!item) return; if(act==='approve'){ item.status='approved'; log(`Approved draft for ${item.account}`); } if(act==='reject'){ item.status='rejected'; log(`Rejected draft for ${item.account}`); } if(act==='copy'){ navigator.clipboard?.writeText(item.draft); log(`Copied draft for ${item.account}`); } if(act==='remove'){ queue=queue.filter(q=>q.id!==id); log(`Removed ${item.account} packet`); } saveQueue(); }
function addToQueue(){ if(!currentPacket) build(); const exists = queue.some(q=>q.playId===currentPacket.playId && q.focus===currentPacket.focus && q.status!=='rejected'); if(exists){ log('Skipped duplicate active packet. Change focus or remove existing queue item.'); return; } queue.unshift(currentPacket); saveQueue(); $('packetStatus').textContent='Queued'; log(`Added to approval queue: ${currentPacket.account}`); }
function exportQueue(){ const rows=[['account','signal','line','lane','focus','priority','confidence','value','buyer','status','summary','draft']].concat(queue.map(q=>[q.account,q.signal,q.line,q.lane,q.focus,q.priority,q.confidence,q.value,q.buyer,q.status,q.summary,q.draft])); const csv=rows.map(r=>r.map(csvEscape).join(',')).join('\n'); const blob=new Blob([csv],{type:'text/csv'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='tcas-revenue-radar-approval-queue.csv'; a.click(); URL.revokeObjectURL(url); log(`Exported ${queue.length} queue rows to CSV`); }
function runDemo(){ $('searchInput').value='Schneider'; $('laneFilter').value='Controls modernization'; renderRadar(); const play=plays.find(p=>p.id==='schneider-modernization'); $('playSelect').value=play.id; $('focusSelect').value='risk'; build(play); addToQueue(); document.querySelector('#builder').scrollIntoView({behavior:'smooth'}); log('Demo workflow: filtered Schneider → built risk packet → queued for approval'); }
function init(){ const lanes=['all',...new Set(plays.map(p=>p.lane))]; $('laneFilter').innerHTML = lanes.map(l=>`<option value="${l}">${l==='all'?'All lanes':l}</option>`).join(''); $('playSelect').innerHTML = plays.map(p=>`<option value="${p.id}">${p.account} — ${p.signal}</option>`).join(''); $('playSelect').onchange=()=>build(plays.find(p=>p.id===$('playSelect').value)); $('focusSelect').onchange=()=>build(currentPlay); $('searchInput').oninput=renderRadar; $('laneFilter').onchange=renderRadar; $('buildBtn').onclick=()=>build(currentPlay); $('addQueueBtn').onclick=addToQueue; $('copyDraftBtn').onclick=()=>{ navigator.clipboard?.writeText($('draft').textContent); log('Copied current email draft'); }; $('copyCrmBtn').onclick=()=>{ navigator.clipboard?.writeText($('crm').textContent); log('Copied current CRM row'); }; $('exportQueueBtn').onclick=exportQueue; $('exportTopBtn').onclick=exportQueue; $('clearQueueBtn').onclick=()=>{ queue=[]; saveQueue(); log('Queue reset'); }; $('demoBtn').onclick=runDemo; $('signalGrid').innerHTML=signalGroups.map(s=>`<article><b>${s[0]}</b><span>${s[1]}</span><em>${s[2]}</em></article>`).join(''); renderRadar(); renderQueue(); updateCounts(); build(plays[0]); initOutreachWriter(); initObsoleteTool(); }


const outreachAngles={
  new_products:{label:'new product / solution update', offer:'a short TCAS product-update review tied to line-card items they may already use', proof:['Uses TCAS-approved manufacturers, not random AI suggestions','Frames a reason to call without pretending plant-specific knowledge','Turns product updates into quote-ready next steps']},
  obsolete:{label:'obsolete parts and replacement path', offer:'a lightweight obsolete-parts screen with replacement, spare, and migration options', proof:['Connects lifecycle risk to distributor revenue','Creates urgent but useful outreach','Keeps exact part verification before quoting']},
  machine_support:{label:'machine support and controls documentation', offer:'a controls/documentation review that turns field photos, BOMs, and old quotes into a supportable parts plan', proof:['Useful to machine builders and manufacturers','Creates service-to-sales conversion','Avoids unsupported engineering claims']},
  vision:{label:'SICK / vision / sensing opportunity', offer:'a sensing/vision fit check for inspection, reject confirmation, case orientation, or quality data', proof:['TCAS can lead with SICK and related sensing lines','Ties to real machine problems','Good for packaging, palletizing, and machine builders']},
  data:{label:'machine data / gateway / reporting wedge', offer:'a small gateway/data-access review using Red Lion, Turck, HMS, Phoenix, or similar TCAS lines', proof:['Creates a first project without full controls rewrite','Good for dormant accounts','Bridges sales and controls credibility']}
};
let currentOutreach=null; let currentMessageType='email';
function getOutreachInputs(){return {account:$('writerAccount').value.trim()||'Wichita-area manufacturer', context:$('writerContext').value.trim(), persona:$('writerPersona').value, angle:outreachAngles[$('writerAngle').value], note:$('writerNote').value.trim()};}
function makeOutreach(){const i=getOutreachInputs(); const safeName=i.account; const offer=i.angle.offer; const proof=i.angle.proof; const note=i.note;
 const email=`Subject: Practical TCAS idea for ${safeName}\n\nHi [Name],\n\nI’m reaching out from TCAS because we work with manufacturers and machine builders around automation parts, controls support, and line-card solutions.\n\nI do not want to assume what you need without seeing the equipment, but ${i.context.toLowerCase()} is exactly the kind of environment where a short review can uncover useful next steps.\n\nThe practical idea: ${offer}.\n\nWhat TCAS can help identify:\n• parts or product families already in the plant/machine\n• obsolete or hard-to-source components\n• replacement paths and spares\n• sensing, safety, HMI, drive, panel, or gateway opportunities\n• what should become a quote now vs. what needs engineering verification\n\n${note}\n\nWould it be worth a 15-minute conversation to see if there is a useful first review we can do?\n\nThanks,\nAndrew / TCAS`;
 const linkedin=`Hi [Name] — I’m with TCAS. We help manufacturers and machine builders turn real machine/controls needs into practical parts and support plans.\n\nFor ${safeName}, I thought there may be a useful angle around ${i.angle.label}: ${offer}.\n\nNo pitch or assumptions — I’d be curious if a short review of current machines, obsolete parts, or controls/sensing needs would be useful.`;
 const call=`Quick opener:\n\n“Hi [Name], this is Andrew with TCAS. I’m not calling with a generic catalog pitch. We’re looking at Wichita-area machine builders and manufacturers where TCAS can help turn real machine issues, obsolete parts, or new product updates into practical replacement and support plans. Is there someone who handles controls, maintenance, or automation parts that I should talk with?”`;
 const voicemail=`Hi [Name], this is Andrew with TCAS. I’m calling because we’re helping manufacturers and machine builders with practical automation parts support: obsolete components, replacement paths, sensing/vision, controls documentation, and quote-ready next steps. I’ll send a short note as well. My number is [phone]. Again, Andrew with TCAS.`;
 const followup=`Follow-up sequence:\n\nDay 1 — Email with specific angle: ${i.angle.label}.\nDay 3 — Call opener asking for engineering/maintenance contact.\nDay 5 — Send one useful checklist: obsolete parts, controls backups, spare drives, sensing/vision, panel/network reliability.\nDay 10 — Short close-the-loop note: “Should I leave this alone, or is there a better person for controls/maintenance/automation parts?”\n\nApproval gate: do not send until TCAS reviews account fit, contact accuracy, and whether the angle is appropriate.`;
 currentOutreach={...i,email,linkedin,call,voicemail,followup,proof}; renderOutreach('email'); log(`Generated outreach for ${safeName} · ${i.angle.label}`);}
function renderOutreach(type=currentMessageType){ if(!currentOutreach) makeOutreach(); currentMessageType=type; document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.message===type)); const labels={email:'Email',linkedin:'LinkedIn',call:'Call opener',voicemail:'Voicemail',followup:'Follow-up sequence'}; $('writerTitle').textContent=labels[type]; $('writerText').textContent=currentOutreach[type]; $('writerProof').innerHTML=currentOutreach.proof.map(x=>`<li>${x}</li>`).join('');}
function addOutreachToQueue(){ if(!currentOutreach) makeOutreach(); const item={id:`outreach-${Date.now()}`, playId:`outreach-${currentOutreach.account}`, created:new Date().toISOString(), account:currentOutreach.account, signal:`Outreach draft: ${currentOutreach.angle.label}`, line:'TCAS business development', lane:'Outreach', priority:'A-', confidence:'Draft needs account verification', value:'Pipeline creation', buyer:currentOutreach.persona, focus:currentOutreach.angle.label, status:'needs_review', summary:`Outreach sequence drafted for ${currentOutreach.account} targeting ${currentOutreach.persona}. Angle: ${currentOutreach.angle.label}.`, pkg:['Email draft','LinkedIn note','Call opener','Voicemail','Follow-up sequence'], draft:currentOutreach.email+'\n\n--- LinkedIn ---\n'+currentOutreach.linkedin+'\n\n--- Call opener ---\n'+currentOutreach.call+'\n\n--- Voicemail ---\n'+currentOutreach.voicemail+'\n\n--- Follow-up ---\n'+currentOutreach.followup, crm:`account: ${currentOutreach.account}\nlane: Outreach\nbuyer: ${currentOutreach.persona}\nangle: ${currentOutreach.angle.label}\nstatus: needs_review\nnext_step: verify contact and approve send`}; queue.unshift(item); saveQueue(); log(`Added outreach draft to approval queue: ${currentOutreach.account}`);}
function initOutreachWriter(){ if(!$('generateOutreachBtn')) return; $('generateOutreachBtn').onclick=makeOutreach; $('copyEmailOutreachBtn').onclick=()=>{ if(!currentOutreach) makeOutreach(); navigator.clipboard?.writeText(currentOutreach.email); log('Copied outreach email'); }; $('copyLinkedInBtn').onclick=()=>{ if(!currentOutreach) makeOutreach(); navigator.clipboard?.writeText(currentOutreach.linkedin); log('Copied LinkedIn outreach'); }; $('addOutreachQueueBtn').onclick=addOutreachToQueue; document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>renderOutreach(b.dataset.message)); ['writerAccount','writerContext','writerPersona','writerAngle','writerNote'].forEach(id=>$(id).addEventListener('input',()=>makeOutreach())); makeOutreach();}

const obsoleteVendors = [
  {vendor:'Banner Engineering', alias:'Banner', confidence:'Medium-high', angle:'Safety module upgrade / spare conversion', status:'Public discontinuation note pattern found', source:'https://info.bannerengineering.com/cs/groups/public/documents/literature/b_4430879.pdf', sourceLabel:'Banner DUO-TOUCH discontinued upgrade note', workflow:['Search exact Banner model on bannerengineering.com','Check product notice / document library','Identify current SG / XS26 / SC26 / safety controller replacement','Verify contacts, safety outputs, voltage, PL/category requirement','Create quote pack with replacement module + button/contact caveats'], example:'AT-FM-2A / AT-AM-2A / AT-BM-2A DUO-TOUCH legacy modules'},
  {vendor:'KEYENCE', alias:'Keyence', confidence:'Medium', angle:'Vision / sensor replacement and new-product conversion', status:'Public discontinuation notice pattern + current new-products page', source:'https://www.keyence.com/landing/lpc/cvx100disc.jsp', source2:'https://www.keyence.com/products/new-products', sourceLabel:'KEYENCE CV-X100 discontinuation notice + new products', workflow:['Search exact KEYENCE model and series','Check KEYENCE discontinuation notice if available','Confirm last order / shipment / repair service dates','Map to current KEYENCE series or TCAS alternative if channel allows','Capture caveat: KEYENCE replacement support often requires direct sales verification'], example:'CV-X100 controllers → CV-X300; repair service ended Sept. 30, 2025'},
  {vendor:'Cognex', alias:'convex / Cognex', confidence:'Manual verification', angle:'Machine vision replacement / barcode reader migration', status:'Treat user “convex” as Cognex unless corrected; public lifecycle lookup not confirmed', source:'https://www.cognex.com', source2:'https://investor.cognex.com/news/news-details/2026/Cognex-Completes-Divestiture-of-JapanFocused-Trading-Business/default.aspx', sourceLabel:'Cognex site + 2026 corporate signal; lifecycle requires manual product lookup', workflow:['Confirm whether “convex” means Cognex','Search exact Cognex model on cognex.com support/products','Check DataMan/In-Sight family docs and support status','Ask Cognex/distribution channel for active replacement','Package customer-safe migration note with vision application risks'], example:'DataMan / In-Sight / barcode or machine vision family requiring manual status check'},
  {vendor:'Eaton', alias:'Eaton', confidence:'High for EOSL workflow', angle:'Power protection / controls replacement planning', status:'Official Eaton EOSL program + master list workflow', source:'https://www.eaton.com/us/en-us/catalog/services/eaton-end-of-service-life--eosl--program.html', source2:'https://www.eaton.com/br/en-us/digital/brightlayer/brightlayer-data-centers-suite/end-of-life-policy.html', sourceLabel:'Eaton EOSL program + Brightlayer EOL policy', workflow:['Search Eaton EOSL master list / catalog / part number','Determine EOSL, end-of-version, end-of-development, or end-of-life','Verify replacement system or current Eaton family','Check service contract / support coverage','Create replacement planning packet'], example:'UPS / Brightlayer / legacy power protection equipment'},
  {vendor:'Rockwell Automation', alias:'Rockwell / Allen-Bradley', confidence:'High', angle:'Lifecycle status, migration, and critical spares', status:'Official lifecycle status and replacement lookup workflow', source:'https://www.rockwellautomation.com/en-us/support/product/product-compatibility-migration/product-lifecycle-status.html', source2:'https://www.vanmeterinc.com/blog/how-to-find-rockwell-automation-product-lifecycle-status', sourceLabel:'Rockwell lifecycle status tool + replacement workflow', workflow:['Search catalog number or family in Rockwell Lifecycle Status','Record status: Active, Active Mature, End of Life, Discontinued','Use replacement lookup / PCDC / ProposalWorks where available','Capture last-time-buy or discontinued date if listed','Create migration / spare / quote packet'], example:'1747 SLC, 1769 CompactLogix, legacy PanelView, discontinued drives'},
  {vendor:'Siemens', alias:'Siemens', confidence:'High for S7-1200 G1 2026 signal', angle:'S7-1200 G1 phase-out and migration to G2', status:'2026 discontinuation/phase-out signal found for S7-1200 G1', source:'https://www.eichler-service.com/en/magazine/article-search/articles/simatic-s7-1200-g1-siemens-announces-product-discontinuation-for-1-november-2026', source2:'https://support.industry.siemens.com/cs/document/91688124/description-of-the-product-lifecycle-for-simatic-hmi-products-(plm)?dti=0&lc=en-WW', sourceLabel:'Siemens S7-1200 G1 phase-out summary + Siemens PLM lifecycle reference', workflow:['Search exact Siemens MLFB / 6ES7 part number in Siemens Industry Mall / support','Identify PLM milestone: P.M300, P.M400, P.M410, P.M490','For S7-1200 G1: flag P.M400 phase-out as of Nov. 1, 2026; new-unit procurement window to Oct. 31, 2027 per source','Map to S7-1200 G2 or current Siemens successor','Create migration and spares plan'], example:'SIMATIC S7-1200 G1 / 6ES7 family → S7-1200 G2'}
];
function initObsoleteTool(){
  if(!$('obsoleteVendor')) return;
  $('obsoleteVendor').innerHTML = obsoleteVendors.map((v,i)=>`<option value="${i}">${v.vendor} (${v.alias})</option>`).join('');
  $('obsoleteVendor').onchange=buildObsoletePacket;
  $('obsoletePart').oninput=buildObsoletePacket;
  $('obsoleteAccount').oninput=buildObsoletePacket;
  $('researchObsoleteBtn').onclick=buildObsoletePacket;
  $('addObsoleteQueueBtn').onclick=addObsoleteToQueue;
  $('copyObsoleteBtn').onclick=()=>{ navigator.clipboard?.writeText($('obsoletePacket').textContent); log('Copied obsolete/discontinued quote pack'); };
  $('exportObsoleteBtn').onclick=exportObsoleteCsv;
  buildObsoletePacket();
}
function selectedObsoleteVendor(){ return obsoleteVendors[Number($('obsoleteVendor').value||0)]; }
function buildObsoletePacket(){
  const v=selectedObsoleteVendor(); const part=$('obsoletePart').value.trim()||'[part number]'; const account=$('obsoleteAccount').value.trim()||'[customer/site]';
  $('obsConfidence').textContent=v.confidence; $('obsAngle').textContent=v.angle.split(' / ')[0];
  const text=`2026 DISCONTINUED / OBSOLETE RESEARCH PACKET\n\nAccount/site: ${account}\nManufacturer: ${v.vendor}\nPart/family: ${part}\nKnown source status: ${v.status}\nConfidence: ${v.confidence}\nSales angle: ${v.angle}\nExample/use case: ${v.example}\n\nResearch workflow:\n${v.workflow.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\nQuote-safe next action:\nVerify exact catalog number, firmware/series, installed application, replacement compatibility, stock/lead time, and safety/controls impact before quoting or emailing customer.\n\nTCAS packet fields to create:\n- lifecycle status\n- discontinued/end-of-life date if available\n- last-time-buy / last-ship / repair window if listed\n- successor/replacement part\n- required compatibility checks\n- TCAS line-card fit\n- inventory/spares action\n- customer-safe outreach draft\n- source URL evidence`;
  $('obsoletePacket').textContent=text;
  $('obsoleteLinks').innerHTML=[v.source,v.source2].filter(Boolean).map((url,i)=>`<a class="btn ghost" target="_blank" rel="noreferrer" href="${url}">${i===0?v.sourceLabel:'Additional source'}</a>`).join('');
  log(`Built obsolete research packet: ${v.vendor} · ${part}`);
}
function addObsoleteToQueue(){
  const v=selectedObsoleteVendor(); const part=$('obsoletePart').value.trim()||'[part number]'; const account=$('obsoleteAccount').value.trim()||'[customer/site]';
  buildObsoletePacket();
  const packet={ id:`obsolete-${Date.now()}`, playId:`obsolete-${v.vendor}-${part}`, created:new Date().toISOString(), account, signal:`Obsolete/discontinued research: ${part}`, line:v.vendor, lane:'Obsolescence research', priority:v.confidence==='High'||v.confidence.startsWith('High')?'A':'B+', confidence:v.confidence, value:'TBD after part/stock check', buyer:'Maintenance / engineering / purchasing', focus:'discontinued product conversion', status:'needs_review', summary:`${account} has a potential discontinued/obsolete ${v.vendor} part or family (${part}). ${v.status}. Sales angle: ${v.angle}.`, pkg:['Lifecycle/source verification','Replacement/successor lookup','Spare/stock/last-time-buy check','Compatibility and migration risk list','Customer-safe quote/update packet'], draft:$('obsoletePacket').textContent, crm:`account: ${account}\nsignal: obsolete/discontinued research\nmanufacturer_line: ${v.vendor}\npart_or_family: ${part}\nlane: Obsolescence research\nconfidence: ${v.confidence}\nsource: ${v.source}\nstatus: needs_review\nnext_step: verify exact part status and replacement before outreach` };
  queue.unshift(packet); saveQueue(); log(`Added obsolete opportunity to queue: ${v.vendor} · ${part}`);
}
function exportObsoleteCsv(){
  const rows=[['vendor','alias','confidence','status','angle','example','primary_source','additional_source']].concat(obsoleteVendors.map(v=>[v.vendor,v.alias,v.confidence,v.status,v.angle,v.example,v.source,v.source2||'']));
  const csv=rows.map(r=>r.map(csvEscape).join(',')).join('\n'); const blob=new Blob([csv],{type:'text/csv'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='tcas-2026-obsolete-research-vendors.csv'; a.click(); URL.revokeObjectURL(url); log('Exported 2026 obsolete vendor research CSV');
}

init();