const plays = [
  { id:'sick-hershey-vision', lane:'Vision / sensing', signal:'SICK Ruler3000 / 3D vision update', account:'Hershey Edgerton', line:'SICK', trigger:'Packaging/palletizing SKU matrix creates case orientation, inspection, reject timing, and quality-data opportunities.', pkg:['3D vision feasibility screen','PLC result mapping','Reject timing verification','Camera/network architecture review'], value:'$18k–$65k', priority:'A', confidence:'High', buyer:'Engineering / packaging operations' },
  { id:'phoenix-tna-network', lane:'Panel reliability', signal:'Phoenix Contact panel reliability kit', account:'TNA Robag / food packaging site', line:'Phoenix Contact', trigger:'Service-network issues and field notes suggest panel power, terminal, switch, and documentation cleanup.', pkg:['24VDC health check','Industrial switch map','Terminal/relay cleanup','Documented service-network path'], value:'$8k–$28k', priority:'B+', confidence:'Medium-high', buyer:'Maintenance / controls' },
  { id:'schneider-modernization', lane:'Controls modernization', signal:'Schneider controls modernization', account:'Schneider-heavy plant panel', line:'Schneider Electric', trigger:'Schneider spans 25 TCAS line-card categories, so one panel review can create PLC/HMI/VFD/safety opportunities.', pkg:['PLC/HMI lifecycle review','VFD spare path','Panel risk report','Software/backup assessment'], value:'$25k–$140k', priority:'A', confidence:'High', buyer:'Plant engineering' },
  { id:'redlion-data', lane:'Data access', signal:'Red Lion / HMS / Turck data access', account:'Warehouse automation prospect', line:'Red Lion / Turck / HMS', trigger:'Customer wants machine data without a full PLC rewrite; gateways create a practical first project.', pkg:['Protocol gateway review','SCADA/OEE signal map','Industrial Ethernet cleanup','Pilot data dashboard'], value:'$12k–$55k', priority:'A-', confidence:'Medium-high', buyer:'Operations / IT-OT' },
  { id:'berobox-palletizer', lane:'Palletizing automation', signal:'beRobox palletizer fit screen', account:'Hershey Edgerton', line:'Palletizing automation', trigger:'Hershey SKU weights/rates make a plug-and-play palletizer screen credible, but safety/control details need verification.', pkg:['SKU/rate fit matrix','Safety + controls checklist','Infeed/outfeed integration scope','Vendor question pack'], value:'$20k–$90k', priority:'A-', confidence:'Medium', buyer:'Packaging engineering' },
  { id:'drives-spares', lane:'Critical spares', signal:'Drive replacement / critical spares', account:'Dormant food plant account', line:'Schneider / Toshiba / Control Techniques', trigger:'Drive failures create urgent buys; proactive spare mapping turns risk into parts revenue.', pkg:['Critical drive inventory','Replacement cross-reference','Spare quote package','Maintenance handoff sheet'], value:'$10k–$75k', priority:'B+', confidence:'Medium', buyer:'Maintenance manager' },
  { id:'hmi-retrofit', lane:'HMI retrofit', signal:'Legacy HMI backup and retrofit campaign', account:'Multi-site manufacturing account', line:'Pro-face / Red Lion / Schneider / IDEC', trigger:'Old HMIs are visible in panel photos and often lack backups, replacement paths, or readable screens.', pkg:['HMI inventory','Backup status check','Replacement path','Operator-screen readability review'], value:'$7k–$45k', priority:'B+', confidence:'Medium', buyer:'Controls engineer' }
];
const focusText = { new_product:'new product / solution update', spares:'critical spares / replacement path', risk:'obsolescence or downtime risk', data:'machine data / reporting wedge', campaign:'multi-account product campaign' };
const signalGroups = [
  ['Schneider Electric','Controls, drives, HMIs, software, safety','Modernization, lifecycle, spares, panel standards'],
  ['SICK','Sensors, safety, encoders, software, 3D vision','Inspection, safety audits, reject issues, quality data'],
  ['Phoenix Contact','Power, relays, terminals, datacom, PLCs','Panel reliability, network documentation, 24V issues'],
  ['Red Lion / Turck / HMS','Gateways, HMIs, I/O, wireless, interfaces','Machine data access, protocol conversion, OT visibility'],
  ['IDEC / Pro-face','HMIs, PLCs, relays, pilot devices','HMI retrofit, operator interface backups'],
  ['Toshiba / Control Techniques / KB','Drives and motion','Critical spare drives, replacements, failure risk']
];
let currentPlay = plays[0];
let currentPacket = null;
let queue = JSON.parse(localStorage.getItem('tcasRevenueRadarQueue') || '[]');
const $ = id => document.getElementById(id);
function log(msg){ const stamp = new Date().toLocaleTimeString([], {hour:'2-digit', minute:'2-digit', second:'2-digit'}); $('actionLog').textContent = `[${stamp}] ${msg}\n` + $('actionLog').textContent.split('\n').slice(0,8).join('\n'); }
function csvEscape(v){ return `"${String(v ?? '').replaceAll('"','""')}"`; }
function saveQueue(){ localStorage.setItem('tcasRevenueRadarQueue', JSON.stringify(queue)); updateCounts(); renderQueue(); }
function updateCounts(){ $('queueCount').textContent = queue.length; $('approvedCount').textContent = queue.filter(q=>q.status==='approved').length; }
function focus(){ return focusText[$('focusSelect').value]; }
function packetFor(play){ const packet = {
  id: `${play.id}-${Date.now()}`,
  playId: play.id,
  created: new Date().toISOString(),
  account: play.account,
  signal: play.signal,
  line: play.line,
  lane: play.lane,
  priority: play.priority,
  confidence: play.confidence,
  value: play.value,
  buyer: play.buyer,
  focus: focus(),
  status: 'needs_review',
  summary: `${play.account} has a ${focus()} opportunity tied to ${play.line}. ${play.trigger} This is line-card pull-through: a manufacturer-specific reason to call, not generic newsletter content.`,
  pkg: play.pkg,
  draft: `Subject: TCAS idea for ${play.account}\n\nHi [Name],\n\nWe saw a ${play.line} update that may matter for your operation. Based on what we know so far, the practical angle is ${focus()}: ${play.trigger}\n\nTCAS can help with:\n${play.pkg.map(x=>'• '+x).join('\n')}\n\nI do not want to assume fit without checking the details. If useful, TCAS can turn this into a short review with current state, recommended path, and quote-ready parts where appropriate.\n\nThanks,\nTCAS`,
  crm: `account: ${play.account}\nsignal: ${play.signal}\nmanufacturer_line: ${play.line}\nlane: ${play.lane}\ncommercial_focus: ${focus()}\nestimated_value: ${play.value}\npriority: ${play.priority}\nconfidence: ${play.confidence}\nbuyer: ${play.buyer}\nstatus: needs_review\nnext_step: verify technical fit and approve outreach`
}; return packet; }
function build(play=currentPlay){ currentPlay = play; currentPacket = packetFor(play); $('priority').textContent = currentPacket.priority; $('value').textContent = currentPacket.value; $('packetStatus').textContent = 'Draft'; $('summary').textContent = currentPacket.summary; $('packageList').innerHTML = currentPacket.pkg.map(x=>`<li>${x}</li>`).join(''); $('draft').textContent = currentPacket.draft; $('crm').textContent = currentPacket.crm; log(`Built packet: ${play.account} · ${play.signal}`); }
function renderRadar(){ const q = $('searchInput').value.toLowerCase(); const lane = $('laneFilter').value; const grid = $('radarGrid'); grid.innerHTML=''; plays.filter(p => (lane==='all'||p.lane===lane) && [p.account,p.signal,p.line,p.lane,p.trigger].join(' ').toLowerCase().includes(q)).forEach(play=>{ const card=document.createElement('article'); card.className='radar-card'; card.innerHTML=`<div class="radar-top"><span>${play.priority} priority</span><span>${play.value}</span></div><h3>${play.signal}</h3><p><b>${play.account}</b> · ${play.line}</p><p>${play.trigger}</p><div class="mini-actions"><button data-action="build">Build play</button><button data-action="queue">Add to queue</button></div>`; card.querySelector('[data-action="build"]').onclick=()=>{ $('playSelect').value=play.id; build(play); document.querySelector('#builder').scrollIntoView({behavior:'smooth'}); }; card.querySelector('[data-action="queue"]').onclick=()=>{ $('playSelect').value=play.id; build(play); addToQueue(); }; grid.appendChild(card); }); if(!grid.children.length){ grid.innerHTML='<div class="empty">No matching plays. Clear search/filter.</div>'; }}
function renderQueue(){ const wrap=$('queueList'); if(!queue.length){ wrap.innerHTML='<div class="empty">No queued packets yet. Click “Add to approval queue” from a play.</div>'; return; } wrap.innerHTML = queue.map(item=>`<article class="queue-item ${item.status}"><div><div class="queue-title">${item.account}</div><div class="queue-meta">${item.signal} · ${item.line} · ${item.value}</div><p>${item.summary}</p></div><div class="queue-controls"><span class="status ${item.status}">${item.status.replace('_',' ')}</span><button data-id="${item.id}" data-act="approve">Approve</button><button data-id="${item.id}" data-act="reject">Reject</button><button data-id="${item.id}" data-act="copy">Copy draft</button><button data-id="${item.id}" data-act="remove">Remove</button></div></article>`).join(''); wrap.querySelectorAll('button').forEach(btn=>btn.onclick=()=>handleQueue(btn.dataset.id, btn.dataset.act)); }
function handleQueue(id, act){ const item=queue.find(q=>q.id===id); if(!item) return; if(act==='approve'){ item.status='approved'; log(`Approved draft for ${item.account}`); } if(act==='reject'){ item.status='rejected'; log(`Rejected draft for ${item.account}`); } if(act==='copy'){ navigator.clipboard?.writeText(item.draft); log(`Copied draft for ${item.account}`); } if(act==='remove'){ queue=queue.filter(q=>q.id!==id); log(`Removed ${item.account} packet`); } saveQueue(); }
function addToQueue(){ if(!currentPacket) build(); const exists = queue.some(q=>q.playId===currentPacket.playId && q.focus===currentPacket.focus && q.status!=='rejected'); if(exists){ log('Skipped duplicate active packet. Change focus or remove existing queue item.'); return; } queue.unshift(currentPacket); saveQueue(); $('packetStatus').textContent='Queued'; log(`Added to approval queue: ${currentPacket.account}`); }
function exportQueue(){ const rows=[['account','signal','line','lane','focus','priority','confidence','value','buyer','status','summary','draft']].concat(queue.map(q=>[q.account,q.signal,q.line,q.lane,q.focus,q.priority,q.confidence,q.value,q.buyer,q.status,q.summary,q.draft])); const csv=rows.map(r=>r.map(csvEscape).join(',')).join('\n'); const blob=new Blob([csv],{type:'text/csv'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='tcas-revenue-radar-approval-queue.csv'; a.click(); URL.revokeObjectURL(url); log(`Exported ${queue.length} queue rows to CSV`); }
function runDemo(){ $('searchInput').value='Schneider'; $('laneFilter').value='Controls modernization'; renderRadar(); const play=plays.find(p=>p.id==='schneider-modernization'); $('playSelect').value=play.id; $('focusSelect').value='risk'; build(play); addToQueue(); document.querySelector('#builder').scrollIntoView({behavior:'smooth'}); log('Demo workflow: filtered Schneider → built risk packet → queued for approval'); }
function init(){ const lanes=['all',...new Set(plays.map(p=>p.lane))]; $('laneFilter').innerHTML = lanes.map(l=>`<option value="${l}">${l==='all'?'All lanes':l}</option>`).join(''); $('playSelect').innerHTML = plays.map(p=>`<option value="${p.id}">${p.account} — ${p.signal}</option>`).join(''); $('playSelect').onchange=()=>build(plays.find(p=>p.id===$('playSelect').value)); $('focusSelect').onchange=()=>build(currentPlay); $('searchInput').oninput=renderRadar; $('laneFilter').onchange=renderRadar; $('buildBtn').onclick=()=>build(currentPlay); $('addQueueBtn').onclick=addToQueue; $('copyDraftBtn').onclick=()=>{ navigator.clipboard?.writeText($('draft').textContent); log('Copied current email draft'); }; $('copyCrmBtn').onclick=()=>{ navigator.clipboard?.writeText($('crm').textContent); log('Copied current CRM row'); }; $('exportQueueBtn').onclick=exportQueue; $('exportTopBtn').onclick=exportQueue; $('clearQueueBtn').onclick=()=>{ queue=[]; saveQueue(); log('Queue reset'); }; $('demoBtn').onclick=runDemo; $('signalGrid').innerHTML=signalGroups.map(s=>`<article><b>${s[0]}</b><span>${s[1]}</span><em>${s[2]}</em></article>`).join(''); renderRadar(); renderQueue(); updateCounts(); build(plays[0]); }
init();